version: '3'

services:
  app:
    build: ./app
    command: python main.py
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env

  db-postgres:
    image: postgres
    restart: always
    ports:
      - '5439:5432'
    volumes:
      - bot:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: trade_bot


volumes:
  bot: